struct MockData {
    static var arrayOfProducts: [Product] = [
        Product(id: 0,
                brand: "Cetaphil",
                name: "Cetaphil Oily Skin Cleanser 473ml",
                image_url:"https://www.lookfantastic.com/images?url=https://static.thcdn.com/productimg/original/13810032-3005204061537885.jpg&format=webp&auto=avif&width=985&height=985&fit=cover",
                price: "3",
                rating: "4.5",
                description: "dfdfffdfd",
                how_to_use: "fddddddfd",
                benefits: "fdssssf",
                full_ingredient_list: "fdaaaaf",
                sustainability: []),
        Product(id: 1,
                brand: "Perricone MD",
                name: "Perricone MD Vitamin C Ester Brightening Serum 30ml",
                image_url:"https://www.lookfantastic.com/images?url=https://static.thcdn.com/productimg/original/13033787-8244875642933507.jpg&format=webp&auto=avif&width=985&height=985&fit=cover",
                price: "9.99",
                rating: "4",
                description: "dfdf",
                how_to_use: "fdfd",
                benefits: "fdf",
                full_ingredient_list: "fdf",
                sustainability: []),
        Product(id: 2,
                brand: "Perricone MD",
                name: "Perricone MD Vitamin C Ester Brightening Serum 30ml",
                image_url:"https://www.lookfantastic.com/images?url=https://static.thcdn.com/productimg/original/13033787-8244875642933507.jpg&format=webp&auto=avif&width=985&height=985&fit=cover",
                price: "9.99",
                rating: "4",
                description: "dfdf",
                how_to_use: "fdfd",
                benefits: "fdf",
                full_ingredient_list: "fdf",
                sustainability: [])
    ]
}
